---
name: AWS EKS Deploy
description: Action to update a Kubernetes deployment image in AWS EKS using Kubectl

inputs:
  aws-role-arn:
    description: The AWS Role to assume and execute actions in the pipeline that interact with AWS services
    required: true
  aws-region:
    description: The region in AWS that we will be working in
    required: false
    default: us-east-1
  aws-session-name:
    description: The AWS session name to use when assuming the AWS Role
    default: github-action-kubectl
    required: false
  eks-cluster-name:
    description: The name of the EKS cluster that is used to call kubeconfig with awscli
    required: true
    default: eks-develop-services
  eks-namespace:
    description: The Kubernetes namespace of the application that is going to be deployed
    required: true
    default: default
  app-name:
    description: The application name that is going to be deployed
    required: true
  image-name:
    description: The name of the application image that is going to be deployed
    required: true
  image-tag:
    description: The tag of the application image that is going to be deployed
    required: true
    default: latest
  kubectl-version:
    description: The kubectl version to install
    required: false
    default: v1.29.1

runs:
  using: composite
  steps:
  - name: Install Kubectl
    uses: azure/setup-kubectl@776406bce94f63e41d621b960d78ee25c8b76ede  # v4.0.1
    with:
      version: ${{ inputs.kubectl-version }}
  - name: Assume AWS IAM Role
    uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a  # v4.3.1
    with:
      aws-region: ${{ inputs.aws-region }}
      role-to-assume: ${{ inputs.aws-role-arn }}
      role-session-name: ${{ inputs.aws-session-name }}
      mask-aws-account-id: false
  - name: Login to Amazon ECR
    uses: aws-actions/amazon-ecr-login@03f1aad4c6c7ffd436567f42f9384779290529bd  # v2.1.7
    id: login-ecr
    with:
      mask-password: true
  - name: Get AWS EKS kubeconfig
    shell: bash
    env:
      CLUSTER: ${{ inputs.eks-cluster-name }}
      REGION: ${{ inputs.aws-region }}
    run: aws eks update-kubeconfig --name "$CLUSTER" --region "$REGION"
  - name: Update image tag of Kubernetes deployment
    shell: bash
    env:
      IMAGE: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.image-name }}:${{ inputs.image-tag }}
      APP: ${{ inputs.app-name }}
      NAMESPACE: ${{ inputs.eks-namespace }}
    run: |
      kubectl set image "deployment/$APP" "$APP=$IMAGE" -n "$NAMESPACE"
