---
name: Manual - Release

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: write
      issues: write
      pull-requests: write
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Setup node
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020  # v4.4.0
      with:
        node-version: "lts/*"
    - name: Copy rules
      run: |
        cp .github/config/.releaserc.json .
    - name: Install dependencies
      run: |
        npm install --location=global semantic-release@23.0.0 \
          @semantic-release/commit-analyzer@11.1.0 \
          @semantic-release/release-notes-generator@12.1.0 \
          conventional-changelog-conventionalcommits@7.0.2
    - name: Release
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
